# 2025 Job Market & Skills Demand Analysis

In [2]:
# Import the Libaries
import pandas as pd
import numpy as np

#  Loading Dataset
df=pd.read_csv("job_market.csv")
df

#  Data Inspection

In [3]:
# Top 5 Data
df.head()

,job_id,job_title,industry,location,salary_usd,skills_required,remote_option,company_size,posting_date
0,1,Quantum Researcher,Quantum Computing,Singapore,175780.0,"Linear Algebra, Quantum Algorithms",No,Large,22-07-2025
1,2,Renewable Energy Engineer,Green Tech,Singapore,137481.0,"Climate Data Analysis, Energy Modeling",Yes,Large,26-09-2025
2,3,Quantum Researcher,Quantum Computing,Tokyo,182081.0,"Linear Algebra, Qiskit",No,Medium,31-12-2025
3,4,Sustainability Analyst,Green Tech,Singapore,113822.0,"Climate Data Analysis, Energy Modeling",No,Large,29-05-2025
4,5,Smart Contract Engineer,Blockchain,London,92575.0,"Rust, Solidity",Yes,Small,30-03-2025

In [4]:
# Get The Data Information 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10003 entries, 0 to 10002
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           10003 non-null  int64
 1   job_title        10003 non-null  object
 2   industry         10003 non-null  object
 3   location         9997 non-null   object
 4   salary_usd       10000 non-null  float64
 5   skills_required  10003 non-null  object
 6   remote_option    10003 non-null  object
 7   company_size     10003 non-null  object
 8   posting_date     10003 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 703.5+ KB

In [5]:
# Checking missing values
df.isnull().sum()

job_id             0
job_title          0
industry           0
location           6
salary_usd         3
skills_required    0
remote_option      0
company_size       0
posting_date       0
dtype: int64

In [6]:
# Checking duplicate values
df.duplicated().sum()

np.int64(3)

# Data Cleaning

In [8]:
# Remove Duplicate
df = df.drop_duplicates()
df

,job_id,job_title,industry,location,salary_usd,skills_required,remote_option,company_size,posting_date
0,1,Quantum Researcher,Quantum Computing,Singapore,175780.0,"Linear Algebra, Quantum Algorithms",No,Large,22-07-2025
1,2,Renewable Energy Engineer,Green Tech,Singapore,137481.0,"Climate Data Analysis, Energy Modeling",Yes,Large,26-09-2025
2,3,Quantum Researcher,Quantum Computing,Tokyo,182081.0,"Linear Algebra, Qiskit",No,Medium,31-12-2025
3,4,Sustainability Analyst,Green Tech,Singapore,113822.0,"Climate Data Analysis, Energy Modeling",No,Large,29-05-2025
4,5,Smart Contract Engineer,Blockchain,London,92575.0,"Rust, Solidity",Yes,Small,30-03-2025
...,...,...,...,...,...,...,...,...,...
9998,9996,Sustainability Analyst,Green Tech,New York,248617.0,"Energy Modeling, Climate Data Analysis",Yes,Small,13-04-2025
9999,9997,Blockchain Developer,Blockchain,New York,104410.0,"Ethereum, Solidity",Yes,Large,03-11-2025
10000,9998,Quantum Software Developer,Quantum Computing,Berlin,200382.0,"Quantum Algorithms, Qiskit",No,Small,23-02-2025
10001,9999,Renewable Energy Engineer,Green Tech,New York,214484.0,"Energy Modeling, Climate Data Analysis",No,Small,08-03-2025
10002,10000,AI Engineer,Ai,Singapore,117307.0,"TensorFlow, Python",Yes,Large,12-08-2025

In [11]:
# Handling Missing Values
df = df.copy()
df['salary_usd'] = df['salary_usd'].fillna(df['salary_usd'].median())
df

,job_id,job_title,industry,location,salary_usd,skills_required,remote_option,company_size,posting_date
0,1,Quantum Researcher,Quantum Computing,Singapore,175780.0,"Linear Algebra, Quantum Algorithms",No,Large,22-07-2025
1,2,Renewable Energy Engineer,Green Tech,Singapore,137481.0,"Climate Data Analysis, Energy Modeling",Yes,Large,26-09-2025
2,3,Quantum Researcher,Quantum Computing,Tokyo,182081.0,"Linear Algebra, Qiskit",No,Medium,31-12-2025
3,4,Sustainability Analyst,Green Tech,Singapore,113822.0,"Climate Data Analysis, Energy Modeling",No,Large,29-05-2025
4,5,Smart Contract Engineer,Blockchain,London,92575.0,"Rust, Solidity",Yes,Small,30-03-2025
...,...,...,...,...,...,...,...,...,...
9998,9996,Sustainability Analyst,Green Tech,New York,248617.0,"Energy Modeling, Climate Data Analysis",Yes,Small,13-04-2025
9999,9997,Blockchain Developer,Blockchain,New York,104410.0,"Ethereum, Solidity",Yes,Large,03-11-2025
10000,9998,Quantum Software Developer,Quantum Computing,Berlin,200382.0,"Quantum Algorithms, Qiskit",No,Small,23-02-2025
10001,9999,Renewable Energy Engineer,Green Tech,New York,214484.0,"Energy Modeling, Climate Data Analysis",No,Small,08-03-2025
10002,10000,AI Engineer,Ai,Singapore,117307.0,"TensorFlow, Python",Yes,Large,12-08-2025

In [12]:
df['location'] = df['location'].fillna('Unknown')

In [14]:
#  Cleaning Text Columns
df['job_title'] = df['job_title'].astype(str).str.strip()

df['industry'] = df['industry'].astype(str).str.strip()

df['location'] = df['location'].astype(str).str.strip()

df['skills_required'] = df['skills_required'].astype(str).str.strip()

df['remote_option'] = df['remote_option'].astype(str).str.strip()

df['company_size'] = df['company_size'].astype(str).str.strip()

In [15]:
# Converting Date Column
df['posting_date'] = pd.to_datetime(df['posting_date'], dayfirst=True)

In [16]:
# Extracting Month and Month Name
df['month'] = df['posting_date'].dt.month
df['month_name'] = df['posting_date'].dt.month_name()

In [17]:
#  Data Transformation for Export
df['skills_required'] = df['skills_required'].str.replace(',', ';')

# Exporting Cleaned Dataset

In [19]:
import csv
df.to_csv("cleaned_job_data.csv", index=False, quoting=csv.QUOTE_ALL)

In [20]:
import os
os.getcwd()

'C:\\Users\\ubaid\\Job_Market_Project'

In [6]:
df = pd.read_csv("cleaned_job_data.csv")
df = df.copy()

In [7]:
# Standardizing Remote Option Values
df['remote_option'] = df['remote_option'].replace({
    'Y': 'Yes',
    'N': 'No'
})

In [8]:
df['remote_option'].unique()

array(['No', 'Yes'], dtype=object)

In [9]:
# Exporting Cleaned Dataset
import csv
df.to_csv("final_cleaned_job_data.csv", index=False, quoting=csv.QUOTE_ALL)

In [10]:
import os
os.getcwd()

'C:\\Users\\ubaid\\Job_Market_Project'